name: upload artifact

on:
    workflow_dispatch:

jobs:
    build:
      runs-on: ubuntu-latest

      steps:
          - uses: actions/checkout@v3
          - name: Set up JDK 1.8
            uses: actions/setup-java@v1
            with:
              java-version: 1.8
          - name: Grant execute permission for gradlew
            run: chmod +x gradlew
          - name: Build with Gradle
            run: ./gradlew build
          - name: Upload Artifact
            uses: actions/upload-artifact@v4
            with: 
              name: greetings-jar
              path: build/libs

    test-run:
      runs-on: ubuntu-latest
      needs: build
      steps:
        - name: Download candidate aritfacts
          uses: actions/download-artifact@v4
          with:
            name: greetings-jar
        - shell: bash
          run: |
            java -jar greetings.jar